name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.15"
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: Tests
        run: go test -mod=vendor -v ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34
          args: --print-issued-lines
